### PR TITLE
Ignore onClick and onMouseDown when there is no scroll

### PR DESCRIPTION
**Pull request by diegocurbelo**
`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null ` is thown when there is no scroll.

### CODE REVIEW

**Comment by rommguy** [comment]
Thanks!
Those methods were changed when I fixed a different issue and I missed this
The fix looks great, I just want to add failing tests to cover this case

**Comment by rommguy** [comment]
@diegocurbelo Can you please give me permissions to your fork, so I can push the new test case ?
I want to add it to the pull request
Thanks

**Comment by diegocurbelo** [comment]
Sure... it's done!

**Comment by rommguy** [comment]
ok, I still can't push, not sure why, I'll merge and than push the test to this repo

**Comment by rommguy** [comment]
Merged, and just pushed the new test case, you can see it in the last commit
Also updated the tags and npm version
Thanks very much for finding the bug and fixing it!
I'd appreciate if you star this repo

**Comment by diegocurbelo** [comment]
Geat... that was really fast, thanks!

**Pull request merged**
