### PR TITLE
Fix scroll thumb visibility on mobile

### PR DESCRIPTION
**Pull request by neocoder**
This PR makes scroll thumb visible when scrolling on mobile device. Also it adds native kinetic scroll on mobile devices.

### CODE REVIEW

**Comment by rommguy** [comment]
Hi @neocoder,
First - thank you very much for contributing to this project.
Can you explain a little what you did in customScroll.js ?
I don't understand why you use debounce - you only call the debounced method once as far as I can tell, so there isn't much point in debouncing it. 
Did you mean to use setInterval instead ?
Is there a touchEnd event too ? why not use it to set the onDrag state to false similar to mouseUp ?

**Comment by neocoder** [comment]
Hi @rommguy , yeah I probably should have included that in the description. 
When I scroll on the mobile, the scroll thumb does not show up. I looked through the code and find that you flip the onDrag flag in onMouseDown handler, but mousedown event is not fired on the mobile. That's why I added onTouchStart handler. I tried to hook to the touchend event to set onDrag to false, but when you scroll, you lift your finger off the screen to make another scroll swipe and touchEnd event is fired. Unfortunately there's no event available which fires when the scroll is stopped so I decided to call the hide function in the onScroll handler and since it's called multiple times during the scroll, I wrapped it with debounce. Debounce waits number of ms ( I set it to 500 ms ) since the last time the wrapped function was called and then executes the original function. The same can be achieved using the setTimeout, but I think it's always better to use existing tested code than write own from scratch.  

> why not use it to set the onDrag state to false similar to mouseUp
I thought about that, but we don't know how much time will the scroll take since the user raises the finger. The scroll thumb will either be showed to long after the scroll is finished or will hide when the content is still scrolling. Or it will flick very often if no timeout is used. 

I hope this shed some light on how the code works. :)

**Comment by rommguy** [comment]
Thanks @neocoder for explaining. 
Now I see that the github diff display confused me - I thought you invoked the debounced method in componentDidMount -  Everything clear now, nice work. 
The only thing that bothers me now is the size of the lodash debounce method, that will be added to the bundle - I really try to keep this library small
I'll merge and build and if it's not significant I'll deploy a new version to npm

**Comment by rommguy** [comment]
ok, it's like I thought - adding debounce adds 3 KB to the bundle increasing it's size from 9.7kb to 12.3
I'll try to write a simplified version of debounce myself, and see if I can reduce it

**Comment by rommguy** [comment]
Hi @neocoder,
I replaced lodash debounce with a simplified version (0.5kb instead of 2.4kb)
Can you please check the code if everything works for you ?
branch name is "native-scroll-debounce"
Thanks

**Comment by neocoder** [comment]
Hi @rommguy,
just checked native-scroll-debounce branch with my code - works great! Thanks. Will you update npm package after marge to the main branch?

**Comment by rommguy** [comment]
Hi @neocoder,
I just published the new version 3.2.2 to npm
Enjoy and thanks again for contributing

**Pull request merged**
