### PR TITLE
Styling and appearance improvements

### PR DESCRIPTION
**Pull request by orangecoloured**
Added customisable css class prefix.
Removed inner thumb.
Added scrollbar track custom class.
Added disappearing scrollbar toggle.

Now if a user uses a custom prefix everything's going to break, because the prefix in the css is hardcoded. It can be fixed by introducing inline styling for everything with ability to add user style objects. But at least now styles have their own namespace.

Also, heavily edited formatting, because eslinter wouldn't allow me to build.

### CODE REVIEW

**Comment by rommguy** [comment]
Hi @orangecoloured ,
I started to review the changes, why did you change all the spaces and added semicolons ?
Can you please revert those changes?
It makes it very hard to understand what changed from the files diff

**Comment by orangecoloured** [comment]
@rommguy 
All the syntax changes were necessary so the linting would stop throwing errors. I couldn't make a build without it, so I had to make those changes.
As for the prefix and styling. As I mentioned above. One way to fix it is to use inline styling, so all the styles would stay in the context of the component.

**Comment by sag1v** [comment]
any progress with this PR? something i can help with?

**Comment by sag1v** [comment]
I think we can close this now as #54 solved it

**Comment by sag1v** [comment]
I think we can close this as #51 solved it

**Pull request closed without merging**
