### PR TITLE
Remove duplicated simpleDebounce implementation

### PR DESCRIPTION
**Pull request by supromikali**
Remove duplicated simpleDebounce implementation while keeping its more advanced implementation (with cancel logic) in a separate file with test coverage

### CODE REVIEW

**Comment by rommguy** [comment]
Hi @supromikali.
Thank you very much for this. I forgot I moved this function to a separate file in order to test it.
Your change is great, maybe also add a test to the cancel functionality?
What do you think?

**Comment by supromikali** [comment]
Hi @rommguy , yes adding a test to the cancel functionality sounds like a good idea, I will try to take care of it in next few days then

**Comment by supromikali** [comment]
@rommguy I have updated PR, could you check my latest commit with a test case please?

**Comment by rommguy** [comment]
@supromikali Thanks for adding that test. Just merged your change to version 4.1.5
Sorry it took me so long to merge.

**Pull request merged**
